all: Ex00 Ex01 Ex02 Ex03 Ex04

Ex00: Ex00.c
	gcc Ex00.c -o Ex00.out

Ex01: Ex01_a.c Ex01_b.c Ex01_c.c
	gcc Ex01_a.c -o Ex01_a.out
	gcc Ex01_b.c -o Ex01_b.out
	gcc Ex01_c.c -o Ex01_c.out

Ex02: Ex02.c
	gcc Ex02.c -o Ex02.out

Ex03: Ex03.c
	gcc Ex03.c -o Ex03.out

Ex04: Ex04.c
	gcc Ex04.c -o Ex04.out

clean:
	rm -rf *.out
