all: Ex01 Ex02

Ex01: Ex01_client.c Ex01_server.c
	gcc Ex01_client.c -o Ex01_client.out
	gcc Ex01_server.c -o Ex01_server.out

Ex02: Ex02_client.c Ex02_server.c
	gcc Ex02_client.c -o Ex02_client.out
	gcc Ex02_server.c -o Ex02_server.out

clean:
	rm -rf *.out
