all: Ex01 Ex02 Ex03 Ex05 Ex06 Ex08

Ex01: Ex01.c
	gcc Ex01.c -o Ex01.out

Ex02: Ex02.c
	gcc Ex02.c -o Ex02.out

Ex03: Ex03.c
	gcc Ex03.c -o Ex03.out

Ex05: Ex05.c
	gcc Ex05.c -o Ex05.out

Ex06: Ex06.c
	gcc Ex06.c -o Ex06.out

Ex08: Ex08.c
	gcc Ex08.c -o Ex08.out

clean:
	rm -rf *.out
